database:
  driver: mysql
  dsn: gotodo:gotodo@tcp(127.0.0.1:33061)/gotodo

http:
  port: 9090

session:
  samesite: SameSiteStrictMode
  secure: false
  cookieName: MYSESSIONID
  idleTimeout: 2h
  lifeTime: 24h