nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Cookie', 'Set-Cookie']
        expose_headers: ['Link', 'Content-Disposition', 'Content-Length', 'Content-Range', 'Content-Type']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/': null
