database:
  driver: inmemory
  preloadFile: database/inmemory/dev-data.csv

http:
  port: 9090

session:
  samesite: SameSiteStrictMode
  secure: false
  cookieName: MYSESSIONID
  idleTimeout: 2h
  lifeTime: 24h